apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golinks          # < name of ingress entry
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-http01"
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix  # pathType no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified
        backend:
          service:
            name: golinks
            port:
              name: www  # < same label as the port in the service tcp file
  tls:
  - hosts:
    - {{ .Values.ingress.hostname | quote }}
    secretName: golinks-tls
