kind: Service
apiVersion: v1
metadata:
  name: golinks
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: golinks
  ports:
  - protocol: TCP
    name: www
    port: 80